module cpu (
    input clk,          // clock for the PC , register bank and secondary memory
    input reset         // needed for resetting the PC
);
   // Wires needed for connecting the modules
    
    // signals for determining the pc_ctrl
    wire branch;            
    wire jal;
    wire jalr;
    wire branch_taken;

    // signal for selecting the inputs for the ALU
    wire alu_src_A;
    wire alu_src_B;

    // signal for whether to write or read from the memory
    wire mem_read;
    wire mem_write;

    // signal for whether to write to the register bank or not
    wire reg_write;

    //
    reg [1:0] pc_ctrl;  // (its declared as reg because its being calculated inside the cpu module)

    // signal for selecting the writeback to the register bank
    wire [1:0] wb_ctrl;

    // signal for the instruction format (used by immediate generator) 
    wire [2:0] instr_format;

    // extened opcode for finding what instruction it is (used my modules external to decoder like alu and memory module)
    wire [2:0] funct3_branch;
    wire [2:0] funct3_mem;

    // signal for choosing the operation to be performed by ALU
    wire [4:0] alu_mode;

    // inputs to the register bank for choosing the registers needed for the instruction
    wire [4:0] rs1;
    wire [4:0] rs2;
    wire [4:0] rd;

    // Inputs of the PC mux where one will  be selected as nextPC of the PC module
    wire [31:0] pc_default;
    wire [31:0] pc_branch;
    wire [31:0] pc_jal;
    wire [31:0] pc_jalr;

    // Programme counter
    wire [31:0] nextPC;
    wire [31:0] PC;

    // immediate generated by the immediate generator
    wire [31:0] immediate;

    // registers with index rs1,rs2
    wire [31:0] ro1;
    wire [31:0] ro2;

    // instruction pointed by the programme counter
    wire [31:0] instr;

    //inputs to the ALU
    wire [31:0] A;
    wire [31:0] B;

    // inputs the write back mux 
    wire [31:0] alu_out;       // used as address
    wire [31:0] read_data;     

    // contains the value being written to the register bank
    wire [31:0] write_back;


    // instantiating PC_mux module
    PC_mux PC_mux_cpu (.pc_ctrl(pc_ctrl), .pc_default(pc_default), .pc_branch(pc_branch), .pc_jal(pc_jal), .pc_jalr(pc_jalr), .nextPC(nextPC));

    // instantiating PC_calc module
    pc_calc pc_calc_cpu (.PC(PC), .immediate(immediate), .ro1(ro1), .pc_default(pc_default), .pc_branch(pc_branch), .pc_jal(pc_jal), .pc_jalr(pc_jalr) );

    // instantiating PC_calc module
    pc pc_cpu (.clk(clk), .reset(reset), .nextPC(nextPC), .PC(PC));

    // instantiating imem module
    imem imem_cpu (.PC(PC), .instr(instr));
    
    // instantiating immgen module
    immgen immgen_cpu (.instr(instr), .instr_format(instr_format), .immediate(immediate));

    // instantiating alu_mux_A module
    alu_mux_A alu_mux_A_cpu (.ro1(ro1), .PC(PC) , .A(A), .alu_src_A(alu_src_A));

    // instantiating alu_mux_B module
    alu_mux_B alu_mux_B_cpu (.alu_src_B(alu_src_B), .ro2(ro2), .immediate(immediate), .B(B));

    // instantiating ALU module
    ALU ALU_cpu (.A(A), .B(B), .funct3_branch(funct3_branch), .branch_taken(branch_taken), .alu_mode(alu_mode), .alu_out(alu_out));

    // instantiating PC_mux
    wb_mux wb_mux_cpu (.alu_out(alu_out), .pc_default(pc_default), .read_data(read_data), .immediate(immediate), .wb_ctrl(wb_ctrl), .write_back(write_back));

    // instantiating sec_memory
    sec_memory sec_memory_cpu (.clk(clk), .address(alu_out), .mem_read(mem_read), .mem_write(mem_write), .funct3_mem(funct3_mem), .write_data(ro2), .read_data(read_data));

    // instantiating register bank
    bank bank_cpu (.reg_write(reg_write), .clk(clk), .ro1(ro1), .ro2(ro2), .write_back(write_back), .rs1(rs1), .rs2(rs2), .rd(rd));

    // instantiating decoder
    decoder decoder_cpu (.instr(instr), .rs1(rs1), .rs2(rs2), .rd(rd), .reg_write(reg_write), .alu_mode(alu_mode), .jalr(jalr), .jal(jal), .branch(branch) , .alu_src_A(alu_src_A), .alu_src_B(alu_src_B), .instr_format(instr_format), .funct3_mem(funct3_mem), .funct3_branch(funct3_branch), .mem_read(mem_read), .mem_write(mem_write), .wb_ctrl(wb_ctrl));


     // PC_mux control signal generation

    always@(*)begin     

        if (jalr) begin

            pc_ctrl = 2'b11;          // PC = (ro1+immediate) & ~1

        end

        else if (jal) begin

            pc_ctrl = 2'b10;          // PC = PC+immediate

        end

        else if (branch && branch_taken) begin

            pc_ctrl = 2'b01;         // PC = PC+immediate

        end

        else begin

            pc_ctrl = 2'b00;         // PC = PC+4

        end

    end

endmodule